### ISSUE TITLE
PCSG00022 - @Field (JP)(NoNPDRM) Dump

### ISSUE THREAD

**Issue by dallenc** [OperationNT414C/DSMotion#2]
Hi,

I have tried enabling the DsMotion Plugin for the above-mentioned title and it does not work in-game. Both Kernel and TitleID plugins have been included in the tai config file but to no avail.

Is this a compatibility issue or a configuration one?

Awaiting your reply,
Thanks!

**Comment by dallenc** [comment]
EDIT: Does the plugin work with NoNpDRM dumps as it is encrypted and not decrypted?

**Comment by OperationNT414C** [comment]
Hello,

Yes, the plugin works on encrypted titles.

I just checked this game and I could say that the plugin "has an impact" on the game but the behavior is wrong: by default, it will quickly stop the ball (you can see the yellow arrow in the opposite direction when you press L+R). I would attribute this wrong behavior to the following limitation (described in the README.MD file):

"Currently, gyroscope data is not exploited during orientation compute (due to drift problems I had when I tried)"

Due to this limitation, I tried to make best compromises for most games but, they are still compromises (not the correct way to solve the issue) and they doesn't properly work for this game.

The only way I found to "play" the game with the plugin current state is to turn the controller upside down (to make the yellow arrow goes in the good direction).

Sorry for the huge limitation... But, as I said in the limitation, if someone wish to improve the current behavior: "Feel free to give help if you have some maths/IMU skills!" :-)

**Comment by dallenc** [comment]
No problem dude! So if i were to flip my controller upside down it would work? Never thought of tt!! Ok i shall give it a go later. 

Hehe keep up the good work though and looking forward to future releases!
