### ISSUE TITLE
3.68 firmware issues 

### ISSUE THREAD

**Issue by Jackolanternvita** [OperationNT414C/DSMotion#4]
I'm trying to get the plugin to work for uncharted the golden abyss. I think I have done everything correctly but it still isn't working. Could there be an issue with the plugin and the latest firmware? 
Thank you for your time. 

Edit: I tried a ps3 controller and it worked. So it's just not working with DS4. But that's not a problem. 
Thank you so much for creating this plugin!

**Comment by nightwishfan1** [comment]
There's definitely a problem for other users who would want to use a dual shock 4 on a pstv upgraded to the latest firmware and exploited via H-encore.  I helped the above user over on the vitahacks sub reddit, and it wasn't immediately clear what was wrong when everything else was sorted out, until he tried a dual shock 3 instead of a 4.  So it seems this plugin is partially compatible with exploited 3.68 pstv units, and may be the same for users on exploited 3.67 pstv units.  Hopefully someone can get you the necessary offsets for each firmware so that these plugins may be updated, and dual shock 4 functionality hopefully returned as well.

**Comment by Jackolanternvita** [comment]
Oooh found something else out. I was playing with the DS4 and tried to do a balance sixaxis bit and it didn't work and I died. I then turned the controller off and on again and then attempted it again and it worked. So rather than it only working with DS3 it seems it works with either as long as you turn the controller on once in game (so off and on again). Problem completely solved !

**Comment by OperationNT414C** [comment]
Hello,
This module doesn't rely on any FW specific offset so the problem is somewhere else.
Thank you for your report. I build a version which can log the module initialization and the controller detection:
[DSMotionKernelLogs.zip](https://github.com/OperationNT414C/DSMotion/files/2216110/DSMotionKernelLogs.zip)
It should create a report file in "ux0:data/dsmotion_k_log.txt". If this file doesn't contain "DS4 connected!" or "DS3 connected!", then nothing will work.
By the way, I think I have an idea of the issue with H-encore: the DSMotion kernel module must be initialized before the controller gets connected because it needs to intercept the "handshake" connection.
But when you start H-encore, the controller is already connected when the kernel module is initialized. So the controller connection will be ignored. A simple by-pass should be to shutdown/restart the controller once H-encore has been started (long press on the PS button, a menu pop ups and allow to shutdown the controller).
I managed also to reproduce this issue with Enso by powering on the controller very early while the PS TV is booting.
Can you confirm me if the by-pass works for your case on H-encore?

**Comment by Jackolanternvita** [comment]
Turning the controller off and on again after starting h-encore solves the problem! Thank you.
