### ISSUE TITLE
Is this compatible with Firmware 3.68 and h-encore

### ISSUE THREAD

**Issue by Waifu4Life** [OperationNT414C/DSMotion#5]
I added the files and configured my config file, but it doesn't work with Rayman Legends: [config.txt](https://github.com/OperationNT414C/DSMotion/files/2252211/config.txt)

**Comment by OperationNT414C** [comment]
Simply disconnect/reconnect the controller once h-encore has been started.

**Comment by Waifu4Life** [comment]
@OperationNT414C 
I started h-encore, turned the controller off and turned it on again. Once I was in the motion control section of Rayman Legends, it still didn't work. That being said, I modified my config file last night from what I posted here:

#Motion Control
ur0:tai/dsmotion.suprx
*PCSB00360

Could this have impacted DSmotion negatively?

**Comment by OperationNT414C** [comment]
The correct order is:

*PCSB00360
ur0:tai/dsmotion.suprx

The affected title ID must appear before before the plugin path. In order to check if your controller is correctly detected, you can use the version "DSMotionKernelLogs.zip" available on this post: https://github.com/OperationNT414C/DSMotion/issues/4

**Comment by Waifu4Life** [comment]
@OperationNT414C 
I'll try it once I get back home and if it doesn't work, I install the DSMotionKernelLogs. BTW, I'm using a DS4.

**Comment by Waifu4Life** [comment]
@OperationNT414C 
Ya, putting back the config the way it was and turning the controller off and on did the trick, thank you.
